### ISSUE TITLE
Restructure to be approachable by non-developers

### ISSUE THREAD

**Issue by bpalmintier** [GMLC-TDC/HELICS-Tutorial#1]
Seems the tutorial repo should jump out as a series of examples. Right now these are buried in the scripts folder, which may make sense for developers but will likely be confusing to use-case users. Would proposes a directory structure that has the series of examples as folders at the top level as in:
* Tutorial-1_Manual-HELICS_Distribution
* Tutorial-2_HELICS-Runner_Transmission-Distribution

**Comment by bpalmintier** [comment]
Additional:
* Tutorial-3_Messages_Transmission-Distribution-Market
* Tutorial-4_Filters_Transmission-Distribution-Market-Communication

Also at the top level could be:
* test_system_data: a rename of "test_system" for clarity
* tests: which would eventually contain some level of unit tests for the tutorial.

**Comment by kdheepak** [comment]
I have a small preference for keeping the root directory lean. Thoughts on the following?

```bash
HELICS-Tutorial
├── README.md
├── tutorials
│  ├── Tutorial-1_Manual-HELICS_Distribution/...
│  └── Tutorial-2_HELICS-Runner_Transmission-Distribution/...
└── test_system_data
   ├── festiv/...
   ├── griddyn/...
   └── gridlabd/...
```

Instead of `Tutorial-*` being in the root, it is in the tutorials folder. I'll update the root README to describe the folder structure more clearly.

**Comment by bpalmintier** [comment]
This seems reasonable. Seems like you have a good start now, excited to also put in the more descriptive tutorial names. At the very least having a number will help guide users to where to start. Eventually we'll want to also have a descriptive markdown file in each example and links to these from the main README.md

**Comment by kdheepak** [comment]
These are the names I have at the moment.

https://gmlc-tdc.github.io/HELICS-Tutorial/tutorials.html

**Comment by bpalmintier** [comment]
Those work. In the description might want to add the HELICS features that are highlighted. e.g. message federates in markets, as part of the quick description. Ideally these descriptions would exist in both README and pages. Pages could have a longer note.

**Comment by kdheepak** [comment]
Restructured to make it more approachable, and added a web friendly way of viewing the tutorial.
